disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - function_parameter_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods